version: '3.8'

# Use 'profiles' to run specific services for different environments
# e.g., `docker compose --profile dev up -d`
services:
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - ./laravel:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - APP_ENV=${APP_ENV:-local}
      - APP_KEY=base64:xV+eR2Q9nL9qX5m8f7k6j4g3h1o0s9z8y7w6v5u4t3s2r1p0o9n8m7l6k5j4i3h2g1f0e
    depends_on:
      - mysql
      - redis
    networks:
      - edu-network
    profiles: ["dev", "prod"]

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - edu-network
    profiles: ["dev", "prod"]

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - edu-network
    profiles: ["dev", "prod"]

  fastapi_worker:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: fastapi_celery_worker
    command: >
      bash -c "celery -A main worker --loglevel=info --concurrency=2"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=mysql+pymysql://${DB_USERNAME}:${DB_PASSWORD}@mysql:3306/${DB_DATABASE}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
    depends_on:
      - redis
      - mysql
    networks:
      - edu-network
    profiles: ["dev", "prod"]

  fastapi_beat:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: fastapi_celery_beat
    command: >
      bash -c "celery -A main beat --loglevel=info --scheduler=celery.beat.PersistentScheduler"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=mysql+pymysql://${DB_USERNAME}:${DB_PASSWORD}@mysql:3306/${DB_DATABASE}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
    depends_on:
      - redis
      - mysql
    networks:
      - edu-network
    profiles: ["dev", "prod"]

volumes:
  mysql-data:

networks:
  edu-network:
    driver: bridge
